; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                  = 10180807-x86_64 Linux               
[ DataSettings ]
datatype                             = snNucleotide                        
containsCodingNuc                    = False                               
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
[ ProcessTypes ]
ppInfer                              = true                                
ppML                                 = true                                
[ AnalysisSettings ]
Analysis                             = Phylogeny Reconstruction            
Statistical Method                   = Maximum Likelihood                  
Phylogeny Test                       = ====================                
Test of Phylogeny                    = Bootstrap method
No. of Bootstrap Replications        = {bootstrap_replications}            
Substitution Model                   = ====================                
Substitutions Type                   = Nucleotide                          
Model/Method                         = {model}                             
Rates and Patterns                   = ====================                
Rates among Sites                    = {rates_among_sites}                 
No of Discrete Gamma Categories      = {gamma_categories}                  
Data Subset to Use                   = ====================                
Gaps/Missing Data Treatment          = {missing_data_treatment}            
Site Coverage Cutoff (%)             = {site_coverage_cutoff}              
Tree Inference Options               = ====================                
ML Heuristic Method                  = {heuristic_method}                  
Initial Tree for ML                  = {initial_tree}                      
Branch Swap Filter                   = {branch_swap_filter}                
System Resource Usage                = ====================                
Number of Threads                    = {threads}                           
Has Time Limit                       = False                               
Maximum Execution Time               = -1                                  
