name: pacu_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.17
  - beautifulsoup4=4.12.2
  - bowtie2=2.5.1
  - figtree=1.4.4
  - gubbins=3.3.1
  - iqtree=2.2.5
  - matplotlib-base=3.8.0
  - minimap2=2.26
  - pandas=2.1.0
  - pyvcf3=1.0.3
  - samtools=1.17
  - seqkit=2.3.1
  - snakemake=7.32.4
  - snp-dists=0.8.2
  - trimmomatic=0.39
  - upsetplot=0.8.0
  - yattag=1.15.1
