; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                              = 10180807-x86_64 Linux           
[ DataSettings ]
datatype                         = snNucleotide                    
containsCodingNuc                = False                           
MissingBaseSymbol                = ?                               
IdenticalBaseSymbol              = .                               
GapSymbol                        = -                               
[ ProcessTypes ]
ppModelSelML                     = true                            
[ AnalysisSettings ]
Analysis                         = Model Selection (ML)            
Tree to Use                      = Automatic (Neighbor-joining tree)
Statistical Method               = Maximum Likelihood              
Substitution Model               = ====================            
Substitutions Type               = Nucleotide                      
Data Subset to Use               = ====================            
Gaps/Missing Data Treatment      = {missing_data_treatment}        
Site Coverage Cutoff (%)         = {site_coverage_cutoff}          
Branch Swap Filter               = {branch_swap_filter}            
System Resource Usage            = ====================            
Number of Threads                = {threads}                       
Has Time Limit                   = False                           
Maximum Execution Time           = -1                              
